version: '3.8'
services:
  server:
    container_name: service
    build:
      context: .
      dockerfile: service/Dockerfile
    volumes:
    - ./service:/usr/src/service
    ports:
      - "8008:8008"
    command: uvicorn service.main:app --host 0.0.0.0 --port 8008 --reload
    environment:
      - PORT=8008
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
  worker:
    build:
      context: .
      dockerfile: service/Dockerfile
    command: celery -A service.worker.celery worker --loglevel=info --logfile=logs/celery.log
    volumes:
      - ./service:/usr/src/service
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - server
      - redis

  redis:
    image: redis:6-alpine

  dashboard:
    build:
      context: .
      dockerfile: service/Dockerfile
    command: celery flower -A worker --broker=redis://localhost:6379/0
    ports:
      - "5556:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - server
      - redis
      - worker

  tests:
    profiles: ["tests"]
    build:
      context: .
      dockerfile: service/Dockerfile
    volumes:
      - .:/usr/src
    command: poetry run pytest -vv --cov .
